core/urls.py
from django.urls import path
#from django.conf.urls import url
from django.urls import re_path as url
import core.views
from .views import (
    ItemDetailView,
    CheckoutView,
    HomeView,
    OrderSummaryView,
    add_to_cart,
    remove_from_cart,
    remove_single_item_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    ProductListView,
    cart_history_view,
    add_to_cart_history,
    robots_txt
)
from django.contrib.sitemaps.views import sitemap
from core.sitemap import StaticViewSitemap, ProductSitemap

sitemaps = {
    'static': StaticViewSitemap,
    'products': ProductSitemap,
}

app_name = 'core'

urlpatterns = [
    path('products_list', ProductListView.as_view(), name='product_list'),
    path('', HomeView.as_view(), name='home'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product'),
    path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,
         name='remove-single-item-from-cart'),
    path('payment/paypal/', PaymentView.as_view(), name='payment'),
    path('payment/stripe/', PaymentView.as_view(), name='payment'),
    #path('payment/vnpay/', VNPAYPaymentView.as_view(), name='vnpay_payment'),
    path('request-refund/', RequestRefundView.as_view(), name='request-refund'),
    path('cart-history/', cart_history_view, name='cart_history'),
    path('add-to-cart-history/', add_to_cart_history, name='add_to_cart_history'),
    #path('payment/vnpay/return/', payment_return, name='vnpay_return'),


    path('vnpay', core.views.index_vnp, name='index'),
    path('payment_vnp', core.views.paymentVNP, name='payment_vnpay'),
    path('payment_ipn', core.views.payment_ipn, name='payment_ipn'),
    path('payment/vnpay_return', core.views.payment_return, name='vnpay_return'),
    path('query', core.views.query, name='query'),
    path('refund', core.views.refund, name='refund'),
    #path('admin/', admin.site.urls),

    path('contact', core.views.contact, name='contact'),

    #sitemap
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    #robot.txt
    path("robots.txt", robots_txt, name="robots_txt")
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse
from django_countries.fields import CountryField
from uuid import uuid4
from imagekit.models import ProcessedImageField
from imagekit.processors import ResizeToFill
from django.contrib.auth.models import User

import vonage


CATEGORY_CHOICES = (
    ('Dr', 'Dress'),
    ('Sh', 'Shoes'),
    ('Gi', 'Gift')
)

LABEL_CHOICES = (
    ('P', 'primary'),
    ('S', 'secondary'),
    ('D', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)


class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    #tim cach luu customer_id lại voi stripe
    stripe_customer_id = 'customer-strpie-key'
    #models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class AdditionImage(models.Model):
    item = models.ForeignKey(
        'Item', 
        related_name='addition_images', 
        on_delete=models.CASCADE
    )
    image = models.ImageField(upload_to='addition_images/')  # Thư mục lưu ảnh bổ sung


class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    #image = models.ImageField()
    image = ProcessedImageField(
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 80}
    )
    custom_id = models.CharField(max_length=255, unique=True, null=True, blank=True, default=uuid4)  # Custom ID
    add_information = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("core:product", kwargs={
            'slug': self.slug
        })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
        })
    
    def get_item_detail(self):
        return AdditionImage.objects.filter(item=self)

class CartHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='cart_history')
    product = models.CharField(max_length=255)
    quantity = models.PositiveIntegerField(default=1)
    price = models.FloatField(default= 0)
    added_at = models.DateTimeField(auto_now_add=True)
    ordered = models.BooleanField(default=False)
    image = ProcessedImageField(
        processors=[ResizeToFill(300, 300)],
        format='JPEG',
        options={'quality': 80},
        null= True,
        blank = True
    )
class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)
    coupon = models.ForeignKey(
        'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total if total > 0 else 0


class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username if self.user else "No user assigned"



class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"


def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)
        # stripe_customer = stripe.Customer.create(email=instance.email)
        # userprofile.stripe_customer_id = stripe_customer['id']
        # userprofile.save()

class PayMent_VNpay(models.Model):
    order_id = models.IntegerField(default=0, null=True,blank= True)
    amount = models.FloatField(default=0.0, null=True, blank=True)
    order_desc = models.CharField(max_length=100,null=True, blank=True)
    vnpay_Trans = models.CharField(max_length=100, null=True, blank=True)
    vnpay_ResponseCode = models.CharField(max_length=100,null=True,blank=True)

class SMSOTP(models.Model):
    result = models.PositiveIntegerField()

    def __str__(self):
        return str(self.result)
    
    def save(self, *args, **kwargs):
        print(f"Saving SMSOTP with result: {self.result}")
        if self.result < 70:
            # Replace with your Vonage API key and secret
            api_key = 'c7d22a24'
            api_secret = 'VSsumT6TeqrfZ9S4'

            # Create a Vonage client
            client = vonage.Client(key=api_key, secret=api_secret)

            # Create a Vonage SMS client
            sms = vonage.Sms(client)

            # Send an SMS message
            responseData = sms.send_message(
                {
                    "from": "Vonage APIs",
                    "to": "+84393241764",  # Replace with your recipient's phone number
                    "text": "A text message sent using the Vonage SMS API",
                }
            )

            # Check the response
            if responseData["messages"][0]["status"] == "0":
                print("Message sent successfully.")
            else:
                print(f"Message failed with error: {responseData['messages'][0]['error-text']}")
        super().save(*args, **kwargs)
post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/base_layout.html
<!DOCTYPE html>
<html lang="en">{% load static %}

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="VNPAY PAYMENT GATEWAY DEMO">
    <meta name="author" content="VNPAY">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static "vnpay_css/css/bootstrap.min.css" %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static "vnpay_css/css/jumbotron-narrow.css" %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!--[if lt IE 9]><script src="{% static "js/ie8-responsive-file-warning.js" %}"></script><![endif]-->
    <script src="{% static "vnpay_css/js/ie-emulation-modes-warning.js" %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{% static "js/ie10-viewport-bug-workaround.js" %}"></script>
</head>

<body>
    <div class="container">
        <div class="header clearfix">
            {% comment %} <nav>
                <ul class="nav nav-pills pull-right">
                    <li role="presentation"><a href="/">Danh sách</a></li>
                    <li role="presentation" class="active"><a href="/CreateOrder">Tạo mới</a></li>

                </ul>
            </nav>{% endcomment %}
            <h3 class="text-muted"><a href="{% url 'core:home' %}">DJANGO-ECOMMERCE</a>
            </a></h3>
        </div>
        {% block content %}
        {% endblock %}

        <footer class="footer">
            <p>&copy; VNPAY {% now "Y" %}</p>
        </footer>
    </div> <!-- /container -->


    <link href="https://pay.vnpay.vn/lib/vnpay/vnpay.css" rel="stylesheet" />
    <script src="https://pay.vnpay.vn/lib/vnpay/vnpay.js"></script>

    <script type="text/javascript">
        $("#btnPopup").click(function () {
            var postData = $("#frmCreateOrder").serialize();
            var submitUrl = $("#frmCreateOrder").attr("action");
            $.ajax({
                type: "POST",
                url: submitUrl,
                data: postData,
                dataType: 'JSON',
                success: function (x) {
                    if (x.code === '00') {
                        vnpay.open({ width: 480, height: 600, url: x.data });
                        return false;
                    } else {
                        alert(x.Message);
                    }
                }
            });
            return false;
        });
    </script>


</body>

</html>

templates/home.html
{% extends "base.html" %}

{% block content %}
<!-- Thêm CSS Bootstrap -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" />

<!-- Thêm thư viện Font Awesome (nếu bạn sử dụng các icon như `fa-graduation-cap`) -->
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" rel="stylesheet" />

<!-- Thêm JavaScript Bootstrap (có chứa các tính năng như carousel) -->
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>

<!-- Thêm CSS của MDB -->
<link href="https://cdn.jsdelivr.net/npm/mdb-ui-kit/css/mdb.min.css" rel="stylesheet" />

<!-- Thêm JS của MDB -->
<script src="https://cdn.jsdelivr.net/npm/mdb-ui-kit/js/mdb.min.js"></script>


<style>
  .carousel-control-next-icon::after {
    content: ">"; /* Thay dấu ">" */
    font-size: 30px;
    color: white;
    font-weight: bold;
  }

  .carousel-control-prev-icon::after {
    content: "<"; /* Thay dấu "<" */
    font-size: 30px;
    color: white;
    font-weight: bold;
  }
</style>

<!-- carousel -->
<div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-mdb-ride="carousel">
  <div class="carousel-indicators">
    <button
      type="button"
      data-mdb-target="#carouselExampleCaptions"
      data-mdb-slide-to="0"
      class="active"
      aria-current="true"
      aria-label="Slide 1"
    ></button>
    <button
      type="button"
      data-mdb-target="#carouselExampleCaptions"
      data-mdb-slide-to="1"
      aria-label="Slide 2"
    ></button>
    <button
      type="button"
      data-mdb-target="#carouselExampleCaptions"
      data-mdb-slide-to="2"
      aria-label="Slide 3"
    ></button>
  </div>
  <div class="carousel-inner" style="width: 100%; height:90%">
    <div class="carousel-item active">
      <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg" class="d-block w-100" alt="Wild Landscape"/>
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
      <div class="carousel-caption d-none d-sm-block mb-5">
        <h1 class="mb-4">
                <strong>Learn Bootstrap 5 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 5. Loved by over 3 000 000 users. Video and written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start free tutorial
                <i class="fas fa-graduation-cap ms-2"></i>
              </a>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%283%29.jpg" class="d-block w-100" alt="Camera"/>
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
      <div class="carousel-caption d-none d-md-block mb-5">
        <h1 class="mb-4">
                <strong>Learn Bootstrap 5 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 5. Loved by over 3 000 000 users. Video and written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start free tutorial
                <i class="fas fa-graduation-cap ms-2"></i>
              </a>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%285%29.jpg" class="d-block w-100" alt="Exotic Fruits"/>
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.4)"></div>
      <div class="carousel-caption d-none d-md-block mb-5">
        <h1 class="mb-4">
                <strong>Learn Bootstrap 5 with MDB</strong>
              </h1>

              <p>
                <strong>Best & free guide of responsive web design</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>The most comprehensive tutorial for the Bootstrap 5. Loved by over 3 000 000 users. Video and written versions
                  available. Create your own, stunning website.</strong>
              </p>

              <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start free tutorial
                <i class="fas fa-graduation-cap ms-2"></i>
              </a>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-mdb-target="#carouselExampleCaptions" data-mdb-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>

  </button>
  <button class="carousel-control-next" type="button" data-mdb-target="#carouselExampleCaptions" data-mdb-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>

  </button>
</div>

<main>
  <div class="container">

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5" >

      <!-- Navbar brand -->
      <span class="navbar-brand" style="color: black" >Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" style="
      justify-content: space-between;
  " id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item {% if not request.GET.category %}active{% endif %}">
            <a class="nav-link" style="color: black !important" href="{% url 'core:product_list' %}">All</a>
          </li>
          <li class="nav-item {% if request.GET.category == 'Dr' %}active{% endif %}">
            <a class="nav-link" style="color: black !important" href="{% url 'core:product_list' %}?category=Dr">Dress</a>
          </li>
          <li class="nav-item {% if request.GET.category == 'Sh' %}active{% endif %}">
            <a class="nav-link" style="color: black !important" href="{% url 'core:product_list' %}?category=Sh">Shoes</a>
          </li>
          <li class="nav-item {% if request.GET.category == 'Gi' %}active{% endif %}">
            <a class="nav-link" style="color: black !important" href="{% url 'core:product_list' %}?category=Gi">Gift</a>
          </li>
        </ul>        
        
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <div class="row wow fadeIn">

        {% for item in object_list %}
        <!--Product 1-->
        <div class="col-lg-3 col-md-6 mb-4">

          <div class="card">

            <div class="view overlay">
              <img class="card-img-top" <img src="{{ item.image.url }}" class="card-img-top">
              <a href="{{ item.get_absolute_url }}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>

            <div class="card-body text-center">
              <a href="" class="grey-text">
                <h5>{{ item.get_category_display }}</h5>
              </a>
              <h5>
                <strong>
                  <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                    {% if item.get_label_display == 'primary' %}
                                <span class="badge badge-pill primary-color">NEW</span>
                                {% elif item.get_label_display == 'secondary' %}
                                <span class="badge badge-pill secondary-color">SALE</span>
                                {% endif %}
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>$
                  {% if item.discount_price %}
                  {{ item.discount_price }}
                  {% else %}
                  {{ item.price }}
                  {% endif %}
                </strong>
              </h4>

            </div>

          </div>

        </div>
        <!--Product 1-->


        {% endfor %}
      </div>

    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->

    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {% endif %}

        <li class="page-item active">
          <a class="page-link" href="?page={{ page_obj.number }}">{{ page_obj.number }}
            <span class="sr-only">(current)</span>
          </a>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
        {% endif %}
      </ul>
    </nav>
    {% endif %}
        <!-- Google Map Section -->
<div class="container mt-5">
  <h4>Find Us Here:</h4>
  <div class="map-container" style="height: 150px;">
    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d11578.025374610213!2d106.69067300200632!3d10.742079626302075!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31752f6f34a62dcd%3A0x207c26a3ce85ff83!2zVmnhu4duIMSQw6BvIHThuqFvIFF14buRYyB04bq_IE5UVCAtIMSQSCBOZ3V54buFbiBU4bqldCBUaMOgbmg!5e0!3m2!1svi!2sus!4v1731582842360!5m2!1svi!2sus" width="100%" height="100%" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
  </div>
</div>

<!-- Newsletter Subscription Form -->
<div class="container mt-5">
  <h4>Subscribe to our Newsletter:</h4>
  <form action="{% url 'core:contact' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="email">Email address:</label>
      <input type="email" class="form-control" id="email" name="email" placeholder="Enter your email" required>
    </div>
    <button type="submit" class="btn btn-primary">Subscribe</button>
  </form>
</div>
    

  </div>
</main>

{% endblock content %}

templates/index.html
{% extends "base_layout.html" %}
{% block content %}
<div class="panel panel-default">
    <!-- Default panel contents -->
    <div class="panel-heading">{{ title }}</div>
    <div class="table-responsive">
        <ul class="list-group">
            <i class="list-group-item"><a href="{% url "core:payment_vnpay" %}">Demo Thanh toán</a></i>
            <i class="list-group-item"><a href="{% url "core:query" %}">Demo Query (Kiểm tra kết quả Giao dịch tại
                    VNPAY)</a></i>
            <i class="list-group-item"><a href="{% url "core:refund" %}">Demo Refund (Gửi yêu cầu hoàn tiền cho giao
                    dịch)</a></i>
        </ul>
    </div>
</div>
{% endblock %}

templates/order_snippet.html
<div class="col-md-12 mb-4">
    <h4 class="d-flex justify-content-between align-items-center mb-3">
    <span class="text-muted">Your cart</span>
    <span class="badge badge-secondary badge-pill">{{ order.items.count }}</span>
    </h4>
    <ul class="list-group mb-3 z-depth-1">
    {% for order_item in order.items.all %}
    <li class="list-group-item d-flex justify-content-between lh-condensed">
        <img src="{{ order_item.item.image.url }}" class="img-fluid" alt="{{ order_item.item.title }}" style="max-width: 100px; height: auto;"> <!-- Chèn hình ảnh -->
        <div>
        <h6 class="my-0"><strong>{{ order_item.quantity }}</strong> x {{ order_item.item.title}}</h6>
        </div>
        <span class="text-muted">${{ order_item.get_final_price }}</span>
    </li>
    {% endfor %}
    {% if order.coupon %}
    <li class="list-group-item d-flex justify-content-between bg-light">
        <div class="text-success">
        <h6 class="my-0">Promo code</h6>
        <small>{{ order.coupon.code }}</small>
        </div>
        <span class="text-success">-${{ order.coupon.amount }}</span>
    </li>
    {% endif %}
    <li class="list-group-item d-flex justify-content-between">
        <span>Total (USD)</span>
        <strong>${{ order.get_total }}</strong>
    </li>
    </ul>

    {% if DISPLAY_COUPON_FORM %}
    <form class="card p-2" action="{% url 'core:add-coupon' %}" method="POST">
        {% csrf_token %}
        <div class="input-group">
            {{ couponform.code }}
            <div class="input-group-append">
            <button class="btn btn-secondary btn-md waves-effect m-0" type="submit">Redeem</button>
            </div>
        </div>
    </form>
    {% endif %}

</div>